version: 0.2
phases:
  install:
    commands:
      - echo "Start Build"
      - printenv
      - echo "End Build"
      - yum install gcc -y
      - make bulid
artifacts:
  files:
    - "userdata/**/*"