version: 0.2
phases:
  install:
    commands:
      - echo "Start Build"
      - printenv
      - echo "End Build"
artifacts:
  name: test
  secondary-artifacts:
    userdata:
      files:
        - "userdata/*"
      name: userdata