---
- name: Enable Epel Repos
  shell: amazon-linux-extras install epel
  become: yes

- name: Install Packages
  package:
    name: "{{item}}"
  with_items:
    - "java-{{java_version}}"
    - tmux
    - htop
    - awscli

- name: Create Folder
  file:
    state: directory
    path: "{{minecraft.installation_path}}"
    recurse: yes

- name: Copy Configuration File
  copy:
    src: "{{item}}"
    dest: "{{minecraft.installation_path}}/{{item}}"
    mode: 0644
  with_items:
    - minecraft_lib.sh
    - stopServer.sh
    - backup.sh
 

- name: Generate Environment File
  template:
    src: minecraft.env.j2
    dest: "{{minecraft.installation_path}}/minecraft.env"

- name: Get the Installer for Chosen Flavor
  get_url:
    url: "{{installers[minecraft.flavor].url}}"
    dest: "{{minecraft.installation_path}}/installer.jar"
    mode: '0755'

- name: Run Minecraft Server Installation
  shell: 
    cmd: "{{installers[minecraft.flavor].install_cmd}}"
    chdir: "{{minecraft.installation_path}}"

- name: Generate the systemd service specification
  template:
    src: minecraft.service.j2
    dest: /etc/systemd/system/minecraft.service

- name: Sync Game World 
  shell: "aws s3 sync s3://{{bucketName}}/saves {{minecraft.installation_path}}"

- name: Start the Service
  systemd:
    name: minecraft
    state: started

- name: Put the backup script in place
  cron:
    name: Backup
    minute: "0"
    hour: "*/1"
    job: "{{minecraft.installation_path}}/backup.sh"

- name: Install mcrcon
  shell: make install
  args:
    chdir: "{{minecraft.installation_path}}/mcrcon"
    
- name: Wait That server is ready for players
  block:
    - name: Wait the server to start and load the map
      wait_for:
        path: "{{minecraft.installation_path}}/logs/latest.log"
        search_regex: "Done"

    - name: Get Public IP of Server
      uri:
        url: http://169.254.169.254/latest/meta-data/public-ipv4
        method: GET
        status_code: [200, 202]
        return_content: true
      register: public_ip

    - name: Notify users that the server is ready
      community.aws.sns:
        msg: "{{lookup('template', 'sns.success.j2')}}"
        subject: Server Minecraft est pret!
        topic: sns-cf-anto-minecraft-server
        region: eu-west-1