installers:
  fabric-1.19:
    url: "https://meta.fabricmc.net/v2/versions/loader/1.19.1/0.14.8/0.11.0/server/jar"
    install_cmd: "echo Installed"
    jar_cmd: "fabric-server-mc.1.19.1-loader.0.14.8-launcher.0.11.0.jar nogui"
  modded:
    url: "http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2831/forge-1.12.2-14.23.5.2831-installer.jar"
    install_cmd: "java -jar {{minecraft.installation_path}}/installer.jar --installServer"
    jar_cmd: "forge-1.12.2-14.23.5.2831-universal.jar nogui"
  modded2:
    url: https://maven.minecraftforge.net/net/minecraftforge/forge/1.16.5-36.2.20/forge-1.16.5-36.2.20-installer.jar
    install_cmd: "java -jar {{minecraft.installation_path}}/installer.jar --installServer"
    jar_cmd: "forge-1.16.5-36.2.20.jar nogui"