---
- hosts: localhost
  tasks:
    - name: Loading Configuration File
      include_vars:
        file: conf.yaml
    - name: Run Minecraft Server Installation
      include_role:
        name: minecraft 