---
- hosts: localhost
  tasks:
    - name: Loading Configuration File
      include_vars:
        file: conf.yaml
    - name: Install Java
      package:
        name: "{{item}}"
      with_items:
        - "java-{{java_version}}"
        - tmux
        - htop
        - awscli
    - name: Create Folder
      file:
        state: directory
        path: "{{minecraft.installation_path}}"
        recurse: yes
    - name: Fabric
      get_url:
        url: "{{fabric_url}}"
        dest: ./fabric.jar
        mode: '0755'

    - name: Copy Configuration File
      copy:
        src: "{{item}}"
        dest: "{{minecraft.installation_path}}/{{item}}"
      with_items:
        - eula.txt
        - server.properties
        - minecraft_lib.sh
    - name: Generate Environment File
      template:
        src: minecraft.env.j2
        dest: "{{minecraft.installation_path}}/minecraft.env"

    - name: Install Scripts
      copy:
        src: "{{item}}"
        dest: "{{minecraft.installation_path}}"
        mode: 0755
      with_items:
        - stopServer.sh

    - name: Run Fabric Installation
      shell: "java -jar ./fabric.jar server -dir {{minecraft.installation_path}} -mcversion {{minecraft.version}} -downloadMinecraft"

    - name: Retrieve Previous Minecraft Server State
      block:
        - name: Get World Backup
          amazon.aws.aws_s3:
            bucket: s3-anto-minecraft-server
            object: world.zip
            dest: "{{minecraft.installation_path}}/world.zip"
            mode: get
        - name: Unzip the world
          unarchive:
            src: "{{minecraft.installation_path}}/world.zip"
            dest: "/"
      rescue:
        - name: No Previous Minecraft Server State
          ansible.builtin.debug:
            msg: "There is no world, let minecraft to create one"

    - name: Generate the systemd service specification
      template:
        src: minecraft.service.j2
        dest: /etc/systemd/system/minecraft.service

    - name: Start the Service
      systemd:
        name: minecraft
        state: started